=== amatiangelo90/backup_hpe/dataloadgen/target/test-classes/CheckList/ref/workflow.dtd
<!--
  ==========================================================================
  Workflow definition DTD.

  Version 1.4
  ==========================================================================
  (c) Copyright 2010 Hewlett-Packard Development Company, L.P.
  ==========================================================================
-->

<!ELEMENT Name            (#PCDATA)>
<!ELEMENT Solution        (#PCDATA)>
<!ELEMENT Description     (#PCDATA)>
<!ELEMENT Init-On-Startup (#PCDATA)>
<!ELEMENT Start-Node      (#PCDATA)>
<!ELEMENT Next-Node       (#PCDATA)>
<!ELEMENT True-Next-Node  (#PCDATA)>
<!ELEMENT False-Next-Node (#PCDATA)>
<!ELEMENT Class-Name      (#PCDATA)>
<!ELEMENT Default-Role    (#PCDATA)>
<!ELEMENT Start-Role      (#PCDATA)>
<!ELEMENT Trace-Role      (#PCDATA)>
<!ELEMENT Kill-Role       (#PCDATA)>
<!ELEMENT Role            (#PCDATA)>
<!ELEMENT State           (#PCDATA)>

<!-- The root for workflow definitions -->

<!ELEMENT Workflow (Name, Solution?, Description?, Default-Role?, 
                    Start-Role?, Trace-Role?, Kill-Role?,
            Start-Node, Nodes, Error-Handler*, 
            End-Handler*, Case-Packet, 
            Initial-Case-Packet?, Contract?, Coordinates?)>
<!ATTLIST Workflow Init-On-Startup CDATA #IMPLIED> 
<!ATTLIST Workflow Unique          CDATA #IMPLIED> 
<!ATTLIST Workflow statEnabled     CDATA #IMPLIED> 
<!ATTLIST Workflow auditEnabled    CDATA #IMPLIED> 
<!ATTLIST Workflow autoAuditEnabled CDATA #IMPLIED> 
<!ATTLIST Workflow disablePersistence CDATA #IMPLIED>
<!ATTLIST Workflow maxNodesPerThread CDATA #IMPLIED>
<!ATTLIST Workflow auditStateChangeEvent CDATA #IMPLIED>

<!-- Nodes -->
<!ELEMENT Nodes ((Process-Node | Rule-Node | Switch-Node)*)>

<!ELEMENT Process-Node (Name, Description?, State?, Role?, Action, Next-Node?)>
<!ATTLIST Process-Node inactive  CDATA #IMPLIED>
<!ATTLIST Process-Node disablePersistence CDATA #IMPLIED>
<!ATTLIST Process-Node test CDATA #IMPLIED>

<!ELEMENT Rule-Node (Name, Description?, State?, Action, 
                     True-Next-Node, False-Next-Node)>
<!ATTLIST Rule-Node disablePersistence CDATA #IMPLIED>

<!ELEMENT Switch-Node (Name, Description?, State?, Action, Switch*, Default)>
<!ATTLIST Switch-Node disablePersistence CDATA #IMPLIED>
<!ELEMENT Switch            (#PCDATA)>
<!ATTLIST Switch name CDATA #IMPLIED>
<!ELEMENT Default (#PCDATA)>


<!-- Actions -->
<!ELEMENT Action (Class-Name, Param*)>
<!ELEMENT Param (#PCDATA)>
<!ATTLIST Param name  CDATA #REQUIRED>
<!ATTLIST Param value CDATA #REQUIRED>

<!-- Handlers -->
<!ELEMENT Error-Handler (Name?, Class-Name, Param*)>
<!ELEMENT End-Handler (Name?, Class-Name, Param*)>

<!ELEMENT Case-Packet (Variable*)>
<!ELEMENT Variable (#PCDATA)>
<!ATTLIST Variable name CDATA #REQUIRED>
<!ATTLIST Variable type CDATA #REQUIRED>
<!ATTLIST Variable disablePersistence CDATA #IMPLIED>

<!ELEMENT Initial-Case-Packet (Variable-Value*)>
<!ELEMENT Variable-Value (#PCDATA)>
<!ATTLIST Variable-Value name  CDATA #REQUIRED>
<!ATTLIST Variable-Value value CDATA #REQUIRED>

<!ELEMENT Contract (Input?, Output?)>
<!ELEMENT Input (Var+)>
<!ATTLIST Input mandatory CDATA #REQUIRED>
<!ELEMENT Output (Var+)>
<!ELEMENT Var    (#PCDATA)>

<!-- Nodes Coordinates -->
<!ELEMENT Coordinates (Position+, Arrows*,State-Circle*)>
<!ELEMENT Position (Name, X, Y, Width, Height)>
<!ELEMENT X      (#PCDATA)>
<!ELEMENT Y      (#PCDATA)>
<!ELEMENT Width  (#PCDATA)>
<!ELEMENT Height (#PCDATA)>

<!ELEMENT Arrows (Name,True-Arrow, False-Arrow,Switch-Arrow?)>
<!ELEMENT True-Arrow (Type,DeltaX,DeltaY)>
<!ELEMENT False-Arrow (Type,DeltaX,DeltaY)>
<!ELEMENT Type   (#PCDATA)>
<!ELEMENT DeltaX (#PCDATA)>
<!ELEMENT DeltaY (#PCDATA)>
<!ELEMENT Switch-Arrow (Default-Arrow, Case-Arrow*)>
<!ELEMENT Case-Arrow (Name, Type, DeltaX, DeltaY)>
<!ELEMENT Default-Arrow (Type, DeltaX, DeltaY)>

<!ELEMENT State-Circle (Name, X, Y, Radius, Color)>
<!ELEMENT Radius (#PCDATA)>
<!ELEMENT Color  (#PCDATA)>

<!--
    (C) 2000-2003 Copyright Hewlett-Packard Development Company, L.P.
-->

=== amatiangelo90/backup_hpe/dataloadgen/src/test/resources/CheckList/ref/echo_cleanVector_TEMPLATE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Workflow SYSTEM "workflow.dtd">
<Workflow Init-On-Startup="false" Unique="false" auditEnabled="true" auditStateChangeEvent="false" autoAuditEnabled="true" disablePersistence="false" statEnabled="true">
   <Name>echo_cleanVector</Name>
   <Solution>TBS_RES</Solution>
   <Start-Node>GetInput</Start-Node>
   <Nodes>
      <Process-Node disablePersistence="true">
         <Name>GetInput</Name>
         <Action>
            <Class-Name>com.hp.ov.activator.mwfm.component.builtin.XMLMapper</Class-Name>
            <Param name="ignore_missing_tags" value="true"/>
            <Param name="input" value="/m:msg/m:body/m:Parameters/m:Parameter/m:value"/>
            <Param name="validate" value="false"/>
            <Param name="xml_var" value="message_data"/>
         </Action>
         <Next-Node>Log Clean Vector</Next-Node>
      </Process-Node>
      <Process-Node disablePersistence="true">
         <Name>Log Clean Vector</Name>
         <Action>
            <Class-Name>com.hp.ov.activator.mwfm.component.builtin.Log</Class-Name>
            <Param name="component_name" value="variable:WORKFLOW_NAME"/>
            <Param name="log_level" value="INFORMATIVE"/>
            <Param name="log_message" value="Reset StateIndexes - The TBS process will start from begin.."/>
         </Action>
         <Next-Node>VariableMapper</Next-Node>
      </Process-Node>
      <Process-Node disablePersistence="true">
         <Name>VariableMapper</Name>
         <Action>
            <Class-Name>com.hp.ov.activator.mwfm.component.builtin.VariableMapper</Class-Name>
            <Param name="response_string" value="TO_REPLACE"/>
         </Action>
      </Process-Node>
   </Nodes>
   <Case-Packet>
      <Variable name="ANNOTATION" type="String"/>
      <Variable name="BREAK_POINT" type="String"/>
      <Variable name="DEADLOCK" type="Boolean"/>
      <Variable name="DEFAULT_ROLE" type="String"/>
      <Variable name="EMPTY_STRING" type="String"/>
      <Variable name="ETC" type="String"/>
      <Variable name="EX_STEP_NAME" type="String"/>
      <Variable name="FILE_URL_PREFIX" type="String"/>
      <Variable name="HOST_NAME" type="String"/>
      <Variable name="JOB_ID" type="Integer"/>
      <Variable name="KILLED" type="Boolean"/>
      <Variable name="KILL_ROLE" type="String"/>
      <Variable name="MACRO_OUTPUT" type="Object"/>
      <Variable name="MASTER_CHILD_JOBS" type="Object"/>
      <Variable name="MUTEX" type="Boolean"/>
      <Variable name="NULL" type="Object"/>
      <Variable name="PRIORITY" type="Integer"/>
      <Variable name="RESERVATIONS" type="Object"/>
      <Variable name="RET_TEXT" type="String"/>
      <Variable name="RET_VALUE" type="Integer"/>
      <Variable name="RUNTIME" type="Object"/>
      <Variable name="SCHEDULED_INFO" type="Object"/>
      <Variable name="SERVICE_ID" type="String"/>
      <Variable name="SOLUTION_ETC" type="String"/>
      <Variable name="SOLUTION_NAME" type="String"/>
      <Variable name="SOLUTION_VAR" type="String"/>
      <Variable name="SOM_INSTANCE" type="Object"/>
      <Variable name="SOM_PATH" type="String"/>
      <Variable name="SOR_ID" type="Integer"/>
      <Variable name="START_ROLE" type="String"/>
      <Variable name="START_TIME" type="Integer"/>
      <Variable name="STATUS" type="String"/>
      <Variable name="STEP_NAME" type="String"/>
      <Variable name="SUBSTEP" type="String"/>
      <Variable name="THROW_EXCEP" type="Boolean"/>
      <Variable name="TIMEOUT" type="Boolean"/>
      <Variable name="TRACE_ROLE" type="String"/>
      <Variable name="UNIQUE_WORKFLOW" type="Integer"/>
      <Variable name="VAR" type="String"/>
      <Variable name="WORKFLOW_EXCEPTION" type="Object"/>
      <Variable name="WORKFLOW_EXECUTION_STATUS" type="String"/>
      <Variable name="WORKFLOW_NAME" type="String"/>
      <Variable name="WORKFLOW_ORDER_ID" type="String"/>
      <Variable name="WORKFLOW_STATE" type="String"/>
      <Variable name="WORKFLOW_TYPE" type="String"/>
      <Variable name="WORKFLOW_VERSION" type="Integer"/>
      <Variable name="accountId" type="String"/>
      <Variable name="action_name" type="String"/>
      <Variable name="activation_description" type="String"/>
      <Variable name="activation_major_code" type="Integer"/>
      <Variable name="activation_minor_code" type="Integer"/>
      <Variable name="anotherResult" type="String"/>
      <Variable name="diagnostics" type="String"/>
      <Variable name="input" type="String"/>
      <Variable name="log_level" type="String"/>
      <Variable name="log_manager" type="String"/>
      <Variable name="major_code" type="String"/>
      <Variable name="major_description" type="String"/>
      <Variable name="message_data" type="String"/>
      <Variable name="message_url" type="String"/>
      <Variable name="minor_code" type="String"/>
      <Variable name="minor_description" type="String"/>
      <Variable name="module_name" type="String"/>
      <Variable name="parent_job_id" type="Integer"/>
      <Variable name="problem_name" type="String"/>
      <Variable name="response_string" type="String"/>
      <Variable name="services" type="Object"/>
      <Variable name="skip_activation" type="Boolean"/>
      <Variable name="sync" type="Boolean"/>
      <Variable name="xmlList" type="String"/>
   </Case-Packet>
   <Initial-Case-Packet>
      <Variable-Value name="FILE_URL_PREFIX" value="file:///"/>
      <Variable-Value name="SOLUTION_NAME" value="TBS_RES"/>
      <Variable-Value name="WORKFLOW_NAME" value="echo_cleanVector"/>
      <Variable-Value name="WORKFLOW_VERSION" value="-1"/>
      <Variable-Value name="diagnostics" value="looooooooooooooooog string"/>
      <Variable-Value name="major_code" value="200"/>
      <Variable-Value name="major_description" value="ok execution"/>
      <Variable-Value name="response_string" value="&lt;Parameters&gt;&lt;Parameter&gt;&lt;attribute&gt;result&lt;/attribute&gt;&lt;value&gt;%inpu%&lt;/value&gt;&lt;type&gt;String&lt;/type&gt;&lt;/Parameter&gt;&lt;/Parameters&gt;"/>
   </Initial-Case-Packet>
   <Contract>
      <Input mandatory="7">
         <Var>parent_job_id</Var>
         <Var>message_data</Var>
         <Var>problem_name</Var>
         <Var>action_name</Var>
         <Var>log_manager</Var>
         <Var>log_level</Var>
         <Var>sync</Var>
      </Input>
      <Output>
         <Var>major_code</Var>
         <Var>minor_code</Var>
         <Var>major_description</Var>
         <Var>minor_description</Var>
         <Var>diagnostics</Var>
         <Var>response_string</Var>
      </Output>
   </Contract>
   <Coordinates>
      <Position>
         <Name>GetInput</Name>
         <X>530</X>
         <Y>149</Y>
         <Width>61</Width>
         <Height>48</Height>
      </Position>
      <Position>
         <Name>Log Clean Vector</Name>
         <X>611</X>
         <Y>149</Y>
         <Width>107</Width>
         <Height>48</Height>
      </Position>
      <Position>
         <Name>VariableMapper</Name>
         <X>739</X>
         <Y>149</Y>
         <Width>100</Width>
         <Height>48</Height>
      </Position>
      <Arrows>
         <Name>GetInput</Name>
         <True-Arrow>
            <Type>0</Type>
            <DeltaX>0</DeltaX>
            <DeltaY>0</DeltaY>
         </True-Arrow>
         <False-Arrow>
            <Type>0</Type>
            <DeltaX>0</DeltaX>
            <DeltaY>0</DeltaY>
         </False-Arrow>
      </Arrows>
      <Arrows>
         <Name>Log Clean Vector</Name>
         <True-Arrow>
            <Type>0</Type>
            <DeltaX>0</DeltaX>
            <DeltaY>0</DeltaY>
         </True-Arrow>
         <False-Arrow>
            <Type>0</Type>
            <DeltaX>0</DeltaX>
            <DeltaY>0</DeltaY>
         </False-Arrow>
      </Arrows>
      <Arrows>
         <Name>VariableMapper</Name>
         <True-Arrow>
            <Type>0</Type>
            <DeltaX>0</DeltaX>
            <DeltaY>0</DeltaY>
         </True-Arrow>
         <False-Arrow>
            <Type>0</Type>
            <DeltaX>0</DeltaX>
            <DeltaY>0</DeltaY>
         </False-Arrow>
      </Arrows>
   </Coordinates>
</Workflow>
